#!/usr/bin/env bash
# Script for the factors challenge

calculate_factors() {
    if [ $# -ne 3 ]; then
        input_args=("$@")
        position_count=0
        factor_product=1

        for arg in ${input_args[*]}; do
            if [ $position_count -gt 1 ]; then
                factor_product=$(echo $arg*$factor_product | bc)
            fi
            position_count=$((position_count + 1))
        done
    else
        factor_product=$3
    fi

    first_number=$2
    converted_num=$(echo "$1" | tr ':' '=')

    comparison_result=$(echo "if($factor_product > $first_number) 1 else 0" | bc)
    if ((comparison_result == 1)); then
        temp_number=$first_number
        first_number=$factor_product
        factor_product=$temp_number
    fi

    echo "$converted_num$first_number*$factor_product"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
else
    while read line; do
        factor_result=$(factor "$line")
        calculate_factors $factor_result
    done < "$1"
fi
