#!/usr/bin/env bash

is_prime() {
    num=$1
    if [ $num -lt 2 ]; then
        return 1
    fi
    for ((i = 2; i * i <= num; i++)); do
        if [ $((num % i)) -eq 0 ]; then
            return 1
        fi
    done
    return 0
}

find_primes() {
    n=$1
    for ((i = 2; i <= n; i++)); do
        if [ $((n % i)) -eq 0 ] && is_prime $i; then
            factor1=$i
            factor2=$((n / i))
            if is_prime $factor2; then
                echo "$n=$factor1*$factor2"
                return
            fi
        fi
    done
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
fi

input_number=$(<"$1")

find_primes $input_number
